edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_profile.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_support.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_variables.scss
edx-platform/pearson-theme/lms/templates/dashboard.html

Includes the latest changes for Pearson theme.
@jfavellar90

Pearson theme update

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_footer.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_variables.scss
edx-platform/pearson-theme/lms/templates/footer.html

colors fix css style
@diegomillan

colors fix css style

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_footer.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_variables.scss

@jfavellar90 
@diegomillan 
change responsive in dashboard 
fix style erros for all links
change link colors for rocket chat

fix error in dashboard-mobile and color for sass

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss

@diegomillan 
@jfavellar90 
change colors for table gradebook 
fix errors for mobile

change colors in gradebook

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss

@diegomillan 
@jfavellar90 
change color for panels in rocket chat and responsive

fix style errors for rocket chat

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_login-register.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_support.scss

@diegomillan 
@jfavellar90 
@ryangadams 
fix errors of style

fix errors style for template

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_footer.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_profile.scss
edx-platform/pearson-theme/lms/templates/dashboard.html
edx-platform/pearson-theme/lms/templates/footer.html
edx-platform/pearson-theme/lms/templates/header/navbar-logo-header.html

@diegomillan 
@jfavellar90 
change aligned and links of footer

change properties of footer

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_footer.scss

delete footer link
@diegomillan

delete link in footer

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss

@nicovanniekerk
@diegomillan
@jfavellar90
change responsive in courses
fix responsive courses about for style in course-profile panel
fix responsive courses instructor view-membership for style in Course Team Management
white spaces of footer in courses section course

change responsive in course

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/templates/dashboard.html

@nicovanniekerk
@diegomillan
@jfavellar90
change colors of buttom
change colors in wiki selection

change colors of bottom

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/pearson-theme/lms/templates/dashboard.html

Pearson Wiki fixes
@diegomillan

Wiki fixes

---

edx-platform/pearson-theme/lms/templates/static_templates/honor.html
edx-platform/pearson-theme/lms/templates/static_templates/privacy.html

Template overrides for privacy and honor pages
@diegomillan

Adding templates to override honor and privacy policy pages

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss

@jfavellar90 
@diegomillan 
issue PE-61
change color of html elements for courses panel

change color and hidden html elements

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss

Adding some styling for rocket chat discussions tab
@diegomillan

Adding some styling for rocket chat discussions tab

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss

SGA Xblock theme  display header color
@diegomillan

SGA Xblock theme  display header color

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_navigation.scss

@nicovanniekerk
@diegomillan
@jfavellar90
white on white  ifx

fix color for link login and register

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_navigation.scss

@ericfab179 
@diegomillan 
align navbar logo with respect to bar in course view

change position of navbar logo

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_footer.scss
edx-platform/pearson-theme/lms/templates/footer.html

@diegomillan 
@diegomillan 
@ericfab179 
change align of footer logos

PE-108 change size and position of footer logo

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_footer.scss
edx-platform/pearson-theme/lms/templates/footer.html

@diegomillan 
@diegomillan 
@ericfab179 
change align of footer logos

change size and position of footer logo

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_navigation.scss

Align logo in responsive view

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_footer.scss

Change responsive in footer elements

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_navigation.scss

@ericfab179 
@diegomillan 
Hide home tab in navigator for courses.

Hide home tab in nav courses.

---

edx-platform/pearson-theme/lms/templates/footer.html

@ericfab179 
@diegomillan 
PE-146
Remove honor code link from the footer.

Remove Honor Code link from footer.

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_navigation.scss
edx-platform/pearson-theme/lms/templates/footer.html

Dev to Staging - PR 86

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_footer.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_navigation.scss
edx-platform/pearson-theme/lms/templates/footer.html

For more info view PR #90 and PR #85.

Dev to master. PE-163

---

ecommerce/africa-legal/templates/edx/checkout/receipt.html
ecommerce/africa-legal/templates/oscar/basket/partials/hosted_checkout_basket.html

- copying receipt template from ecommerce to africa legal
- changing wording in both edx/checkout/recipt.html and oscar/basket/partials/hosted_checkout_basket.html
Is copying the receipt.html page to here correct? 
The other changes are just text so should be safe (i hope)

Changing wording on basket and receipt page as per feedback from ALS

---

ecommerce/africa-legal/templates/customer/emails/commtype_course_seat_purchased_body.html
ecommerce/africa-legal/templates/customer/emails/commtype_course_seat_purchased_body.txt
ecommerce/africa-legal/templates/customer/emails/commtype_course_seat_purchased_subject.txt
ecommerce/africa-legal/templates/edx/checkout/receipt.html
ecommerce/africa-legal/templates/oscar/basket/partials/hosted_checkout_basket.html

- making T&Cs open in new tab
- email wording updated
- link to dashboard now say “go to your courses”

Template changes to payment flow for Africa Legal

---

ecommerce/africa-legal/templates/customer/emails/commtype_course_seat_purchased_body.html
ecommerce/africa-legal/templates/customer/emails/commtype_course_seat_purchased_body.txt
ecommerce/africa-legal/templates/oscar/checkout/payment_pending.html

@andrey-canon @ericfab179 can you review this change? I'm not able to test it locally, and I'm not sure if the change to the pending template will work properly (the start_link template variable)

Pending page and confirmation email changes

---

edx-platform/cabinet-theme/lms/static/sass/partials/lms/theme/_extras.scss

Fix width for index-courses.

---

edx-platform/cabinet-theme/lms/static/sass/partials/lms/theme/_course.scss
edx-platform/cabinet-theme/lms/templates/dashboard.html
edx-platform/cabinet-theme/lms/templates/registration/account_activation_sidebar_notice.html

Fix error caused by the activation message.

---

edx-platform/cabinet-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/cabinet-theme/lms/static/sass/partials/lms/theme/_navigation.scss
edx-platform/cabinet-theme/lms/templates/ace_common/edx_ace/common/base_body.html

Add logo cabinet and styles.
Fix error on language selector.

Email body and language selector Cabinet

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/templates/courseware/course_about.html
edx-platform/pearson-theme/lms/templates/courseware/course_about_sidebar_header.html

Changes for course about page
Add enroll button on bottom  
Hide start date when course is self paced or date is past. Show pay price from studio advanced settings cosmetic price with the right currency
Fix styles for mobile

Ama pe-335

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/pearson-theme/lms/templates/courseware/course_about.html

Fix conflicts on variables to show price from cosmetic studio and start date course. Fix styles for bottom button.

Fix bugs on pe-335

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_courses.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/pearson-theme/lms/templates/courseware/course_about.html
edx-platform/pearson-theme/lms/templates/courseware/course_about_sidebar_header.html

Master to Staging PE-335 fixes

---

edx-platform/cabinet-theme/lms/templates/main.html

This PR updates the Google Analytics track code, in order to send custom events to GA.

PE-373 - Update Google Analytics track code.

---

edx-platform/cabinet-theme/lms/static/sass/partials/lms/theme/_extras.scss

PE-452 Change input color for sga

---

edx-platform/teachfirst-theme/lms/templates/courses_list.html

This PR adds the new carousel implementation to the courses_list.html template.

MIGRATION-39 - Adding new carousel implementation.

---

edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss

Fix text alignment on certificates

certificate fix

---

edx-platform/cabinet-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_extras.scss

Pearson certificate fix

---

ecommerce/pols/templates/edx/error.html
ecommerce/pols/templates/edx/receipt.html
edx-platform/pearson-pols-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
edx-platform/pearson-pols-theme/lms/static/sass/partials/lms/theme/_index.scss
edx-platform/pearson-pols-theme/lms/static/sass/partials/lms/theme/_navigation.scss
edx-platform/pearson-pols-theme/lms/templates/dashboard/_dashboard_course_listing.html

Fix course card spacing and checkout screen redirect

Pearson theme updates

---

edx-platform/teachfirst-theme/lms/templates/help_modal.html

This PR fixes an bug when a user sent a support ticket of Make a suggestion or Ask a question, to show the "Thank you" feedback modal when a ticket was sent successfully.

PE-494 - Fixing bug with the feedback modal.

---

edx-platform/pearson-pols-theme/lms/templates/course_experience/course-outline-fragment.html

Add course-outline-fragment template

PE-356 Add course experience template

---

edx-platform/pearson-pols-theme/lms/static/sass/partials/lms/theme/_login-register.scss
edx-platform/pearson-pols-theme/lms/templates/header/navbar-not-authenticated.html

Hi @danelle-wessels, can you give me your feedback here? Now the URLs come from site config variables and point directly to Okta IPD.
Thanks

changing login and registration url - POLS

---

edx-platform/pearson-pols-theme/lms/static/sass/partials/lms/theme/_login-register.scss
edx-platform/pearson-pols-theme/lms/templates/header/navbar-not-authenticated.html

Fixing logic for urls | reverting login-registration form changes

---

edx-platform/pearson-pols-theme/lms/static/js/bootstrap.js
edx-platform/pearson-pols-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/pearson-pols-theme/lms/templates/header/header.html
edx-platform/pearson-pols-theme/lms/templates/header/navbar-authenticated.html
edx-platform/pearson-pols-theme/lms/templates/header/user_dropdown.html
edx-platform/pearson-pols-theme/lms/templates/help_modal.html

Add support button and remove help button.

PE-612 Add support button.

---

edx-platform/pearson-pols-theme/lms/templates/ccx/coach_dashboard.html
edx-platform/pearson-pols-theme/lms/templates/ccx/course_name.html

This PR adds the coach_dashboard.html template and a new feature to allow the course coach to rename his CCX course.

PE-661 - Adding the coach_dashboard template and new feature to change the CCX course name.

---

edx-platform/pearson-pols-theme/lms/templates/index.html
edx-platform/pearson-pols-theme/lms/templates/learner-achievements-fragment.html

Get app links from site configuration
Remove Course explore button

PE-687, PE-685 Get app links from site configurations 

---

edx-platform/pearson-pols-theme/lms/templates/ccx/coach_dashboard.html

This PR adds the coach_dashboard.html of the Ginkgo version and removes the Ironwood version.

PE-661 - Patch-1 - Adding coach_dahsboard Ginkgo template.

---

edx-platform/pearson-pols-theme/lms/templates/header/user_dropdown.html
edx-platform/pearson-pols-theme/lms/templates/help_modal.html

Use configuration helpers on the help_modal.html and use external link for support button.

PE-707 Drop-down support button

---

edx-platform/pearson-pols-theme/lms/templates/ccx/enrollment.html

Add enrollment.html file
- Hiding staff emails
- Remove revoke button.

PE-732 and PE-733 Add enrollment.html file

---

edx-platform/pearson-pols-theme/lms/templates/ccx/enrollment.html

Only show the email if the user has the role "student"

PE-732 Don't show instructor and staff emails 

---

edx-platform/pearson-pols-theme/lms/templates/ccx/coach_dashboard.html
edx-platform/pearson-pols-theme/lms/templates/courseware/tabs.html

Add tabs file and modify the ccx tab name.

PE-734 Modify ccx tab name

---

edx-platform/teachfirst-theme/lms/static/sass/partials/lms/theme/_extras.scss

Change font for vertical title

PE-586 Change font for vertical title

---

edx-platform/pearson-pols-theme/lms/templates/header/user_dropdown.html

Open the external support link in a new tab

PE-760 Open support link in a new tab

---

edx-platform/pearson-pols-theme/lms/templates/header/navbar-not-authenticated.html

PE-768 Fix responsive menu.

---

ecommerce/pols/templates/edx/error.html

Add support link to error message.

PE-741 Add support link to error message.

---

edx-platform/pearson-pols-theme/lms/templates/dashboard/_dashboard_course_listing.html

Use other_course_settings  to validate if the course is external and avoid to use is_external_course custom method

Migration bug, external courses fix

---

edx-platform/pearson-pols-theme/lms/templates/header/header.html

Add Google tag manager snippet to the header template.

PE-787 Ginkgo Add Google tag manager snippet to the header template.

---

edx-platform/teachfirst-theme/lms/static/sass/partials/lms/theme/_button.scss
edx-platform/teachfirst-theme/lms/templates/ace_common/edx_ace/common/base_body.html

Change buttons backgroung and fix logo url.

PE-777, PE-712, PE-792, Change buttons color and fix logo url.

---

ecommerce/pols/templates/oscar/basket/basket.html

Add custom settings in order to get the GOOGLE_TAG_MANAGER_SNIPPET.

PE-787-ecommerce get GOOGLE_TAG_MANAGER_SNIPPET.

---

edx-platform/pearson-pols-theme/lms/templates/ccx/course_name.html

Add ALTERNATIVE_STRING setting to the ccx course_name template.

PE-734 Add alternative strings to the ccx course_name.html

---

edx-platform/teachfirst-theme/lms/static/sass/partials/lms/theme/_button.scss

PE-792 Change background color.

---

edx-platform/teachfirst-theme/lms/templates/ace_common/edx_ace/common/base_body.html

Add inline style to the logo image and remove styles block(This is not working)

PE-712 Add inline style to the logo image

---

edx-platform/pearson-pols-theme/lms/static/sass/partials/lms/theme/_dashboard.scss
edx-platform/pearson-pols-theme/lms/templates/dashboard.html

Add search input field on dashboard page.

PE-788 Add search input field on dashboard page.

---

edx-platform/pearson-pols-theme/lms/templates/dashboard.html

Hide the container instead of hide the li element in order to avoid black spaces.

PE-788 Fix empty space

---

edx-platform/pearson-pols-theme/lms/templates/header/header.html

Add Google tag manager snippet to the header template.

PE-787 IR Add Google tag manager snippet t the header template.

---

ecommerce/pols/templates/oscar/basket/basket.html

Add custom settings in order to get the GOOGLE_TAG_MANAGER_SNIPPET.
https://github.com/proversity-org/proversity-openedx-themes/pull/250

MIGRATION - PE-787 - Add GOOGLE_TAG_MANAGER_SNIPPET to ecommerce.

---

edx-platform/pearson-pols-theme/lms/static/sass/partials/lms/theme/_extras.scss

Fix tabpanel learner profile styles

PE-786 Fix tabpanel learner profile styles

---

edx-platform/pearson-lbs-theme/lms/static/css/style.css

PE-807 Fix login styles

---

edx-platform/pearson-lbs-theme/lms/static/css/style.css

Change styles for register and login page.

PE-831 Fix register page styles.

---

edx-platform/pearson-lbs-theme/lms/static/css/style.css
edx-platform/pearson-pols-theme/lms/templates/header/navbar-not-authenticated.html

PE 828 Fix not-authenticated header.

---

edx-platform/pearson-lbs-theme/lms/static/css/style.css
edx-platform/pearson-lbs-theme/lms/templates/user_dropdown.html
edx-platform/pearson-theme/lms/static/sass/partials/lms/theme/_index.scss

- Remove unused dropdown option PE-835
- Change title color  PE-833

PE-835 PE-833 Fixing style and remove dropdown option.

---

edx-platform/pearson-lbs-theme/lms/templates/user_dropdown.html

Remove unused dropdown option if bootstrap is not used.

PE-835 Remove unused dropdown option if bootstrap is not used

---

edx-platform/pearson-pols-theme/lms/templates/courseware/course_navigation.html

This PR adds the course_navigation.html template, also adds support for ALTERNATIVE_STRINGS to amend the course tabs names.

PE-811 - Adding the course_navigation.html template.

---

edx-platform/teachfirst-theme/lms/static/sass/partials/lms/theme/_button.scss

Change hover background for recap button.

PE-792 Update styles for recap.

---

edx-platform/cabinet-theme/lms/static/sass/partials/lms/theme/_extras.scss
edx-platform/cabinet-theme/lms/templates/courses_list.html

move carousel logic into python block.

PE-849 move carousel logic into python block.

---

ecommerce/pols/templates/edx/checkout/receipt.html

@Squirrel18 
Works with : [ecomm-40](https://github.com/proversity-org/ecommerce/pull/40)

Adding google tag manager snippet (receipt template).
